# Build Stage
FROM golang:1.19.2-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN  GOOS=linux GOARCH=amd64 go build -o main .

# Final Stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main ./main

ENV PORT = 8080  # Replace with your service port

ENTRYPOINT ["/app/main"]
